name: Python Tests CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - 'api/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'api/**'

env:
  PYTHON_VERSION: '3.10'
  WORKING_DIRECTORY: 'api'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v4

    - name: 'Setup Python ${{ env.PYTHON_VERSION }}'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Cache pip dependencies'
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: 'Install dependencies'
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 'Run tests with pytest'
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        python -m pytest --verbose --tb=short

    - name: 'Generate test report'
      working-directory: ${{ env.WORKING_DIRECTORY }}
      if: always()
      run: |
        python -m pytest --junitxml=test-results.xml --verbose

    - name: 'Upload test results'
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: ${{ env.WORKING_DIRECTORY }}/test-results.xml
